version: '3.12'

services:
  web:
    build: .
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - OTEL_SERVICE_NAME=chatwoot-dify-web
      - DEBUG=False  # Force this to be False
      - DB_HOST=db   # Force the host
      - DB_PORT=5432 # Force the port
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      celery_worker:
        condition: service_started
    env_file:
      - .env

  celery_worker:
    build: .
    command: celery -A app.tasks worker --loglevel=info --concurrency=4 --pool=prefork
    volumes:
      - .:/app
    environment:
      - OTEL_SERVICE_NAME=chatwoot-dify-worker
      - DEBUG=False  # Force this to be False
      - DB_HOST=db   # Force the host
      - DB_PORT=5432 # Force the port
    depends_on:
      - redis
    env_file:
      - .env

  db:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"

  redis:
    container_name: chatwoot_dify_redis
    image: redis:6-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "6380:6379"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # UI
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true

volumes:
  postgres_data:
